name: ci-cd

on:
  push:

jobs:
  test-stack-creation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Validate terraform Templates
      run: |
        pwd